### ISSUE TITLE
binary for 64bit

### ISSUE THREAD

**Issue by ArifBS** [soonuse/jwiringpi#1]
Hello, I got error when running on my 64 bit PI

Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/libc4jwiringpi.so: /usr/lib/libc4jwiringpi.so: wrong ELF class: ELFCLASS32 (Possible cause: can't load ARM .so on a AARCH64 platform)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at jwiringpi.JWiringPiLibraryLoader.load(JWiringPiLibraryLoader.java:47)
	at jwiringpi.JWiringPiController.<clinit>(JWiringPiController.java:43)

seems the the system expect to load the 64-bit on so file. Can you guide me on how to compile to 64-bit?

thanks in advance

**Comment by ArifBS** [comment]
Hello, pls disregard this issue :)
seems you have already wrote it inside the jwiringpi-native folder.

thanks!
